openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /dishes/{id}/ingredients:
    put:
      tags:
      - dish-controller
      operationId: updateDishIngredients
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Ingredient"
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /dishes:
    get:
      tags:
      - dish-controller
      operationId: getAllDishes
      parameters:
      - name: name
        in: query
        required: false
        schema:
          type: string
      - name: priceUnder
        in: query
        required: false
        schema:
          type: number
          format: double
      - name: priceOver
        in: query
        required: false
        schema:
          type: number
          format: double
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    post:
      tags:
      - dish-controller
      operationId: createDishes
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/DishCreateRequestDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /ingredients:
    get:
      tags:
      - ingredient-controller
      operationId: getAllIngredients
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /ingredients/{id}:
    get:
      tags:
      - ingredient-controller
      operationId: getIngredientById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /ingredients/{id}/stock:
    get:
      tags:
      - ingredient-controller
      operationId: getStockValue
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: at
        in: query
        required: false
        schema:
          type: string
      - name: unit
        in: query
        required: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
components:
  schemas:
    Ingredient:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        price:
          type: number
          format: double
        category:
          type: string
          enum:
          - VEGETABLE
          - ANIMAL
          - MARINE
          - DAIRY
          - OTHER
    DishCreateRequestDto:
      type: object
      properties:
        name:
          type: string
        dishType:
          type: string
          enum:
          - START
          - MAIN
          - DESSERT
        sellingPrice:
          type: number
          format: double
