spring.application.name=restaurant-api
spring.datasource.username=product_manager_user
spring.datasource.password=ProducT8_8ManageR8_8User
spring.datasource.url=jdbc:postgresql://localhost:5432/product_management_db
spring.datasource.driver-class-name=org.postgresql.Driver